/** @type {import('tailwindcss').Config} */
const { createThemes } = require('tw-colors');
const defaultTheme = require('tailwindcss/defaultTheme')
const colors = require('tailwindcss/colors')

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        'sans': ['"Montserrat"', ...defaultTheme.fontFamily.sans],
      },
    }
  },
  plugins: [
    createThemes({
      light: {
        primary: colors.blue[600],
        secondary: colors.blue[800],
        accent: colors.zinc[200],
        text: colors.zinc[700],
        bottom: colors.zinc[50],
        'box-bottom': colors.zinc[200],
        'strong-bottom': colors.zinc[300],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      dark: {
        primary: colors.blue[50],
        secondary: colors.blue[200],
        accent: colors.zinc[400],
        text: colors.zinc[50],
        bottom: colors.zinc[900],
        'box-bottom': colors.zinc[800],
        'strong-bottom': colors.zinc[700],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'purple-l': {
        primary: colors.purple[600],
        secondary: colors.purple[800],
        accent: colors.zinc[200],
        text: colors.zinc[700],
        bottom: colors.purple[50],
        'box-bottom': colors.purple[200],
        'strong-bottom': colors.purple[300],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'purple-d': {
        primary: colors.purple[50],
        secondary: colors.purple[200],
        accent: colors.zinc[400],
        text: colors.zinc[50],
        bottom: colors.purple[900],
        'box-bottom': colors.purple[800],
        'strong-bottom': colors.purple[700],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'pink-l': {
        primary: colors.pink[600],
        secondary: colors.pink[800],
        accent: colors.zinc[200],
        text: colors.zinc[700],
        bottom: colors.pink[50],
        'box-bottom': colors.pink[200],
        'strong-bottom': colors.pink[300],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'pink-d': {
        primary: colors.pink[50],
        secondary: colors.pink[200],
        accent: colors.zinc[400],
        text: colors.zinc[50],
        bottom: colors.pink[900],
        'box-bottom': colors.pink[800],
        'strong-bottom': colors.pink[700],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'fuchsia-l': {
        primary: colors.fuchsia[600],
        secondary: colors.fuchsia[800],
        accent: colors.zinc[200],
        text: colors.zinc[700],
        bottom: colors.fuchsia[50],
        'box-bottom': colors.fuchsia[200],
        'strong-bottom': colors.fuchsia[300],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'fuchsia-d': {
        primary: colors.fuchsia[50],
        secondary: colors.fuchsia[200],
        accent: colors.zinc[400],
        text: colors.zinc[50],
        bottom: colors.fuchsia[900],
        'box-bottom': colors.fuchsia[800],
        'strong-bottom': colors.fuchsia[700],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'emerald-l': {
        primary: colors.emerald[600],
        secondary: colors.emerald[800],
        accent: colors.zinc[200],
        text: colors.zinc[700],
        bottom: colors.emerald[50],
        'box-bottom': colors.emerald[200],
        'strong-bottom': colors.emerald[300],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'emerald-d': {
        primary: colors.emerald[50],
        secondary: colors.emerald[200],
        accent: colors.zinc[400],
        text: colors.zinc[50],
        bottom: colors.emerald[900],
        'box-bottom': colors.emerald[800],
        'strong-bottom': colors.emerald[700],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'teal-l': {
        primary: colors.teal[600],
        secondary: colors.teal[800],
        accent: colors.zinc[200],
        text: colors.zinc[700],
        bottom: colors.teal[50],
        'box-bottom': colors.teal[200],
        'strong-bottom': colors.teal[300],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'teal-d': {
        primary: colors.teal[50],
        secondary: colors.teal[200],
        accent: colors.zinc[400],
        text: colors.zinc[50],
        bottom: colors.teal[900],
        'box-bottom': colors.teal[800],
        'strong-bottom': colors.teal[700],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'sky-l': {
        primary: colors.sky[600],
        secondary: colors.sky[800],
        accent: colors.zinc[200],
        text: colors.zinc[700],
        bottom: colors.sky[50],
        'box-bottom': colors.sky[200],
        'strong-bottom': colors.sky[300],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'sky-d': {
        primary: colors.sky[50],
        secondary: colors.sky[200],
        accent: colors.zinc[400],
        text: colors.zinc[50],
        bottom: colors.sky[900],
        'box-bottom': colors.sky[800],
        'strong-bottom': colors.sky[700],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'amber-l': {
        primary: colors.amber[600],
        secondary: colors.amber[800],
        accent: colors.zinc[200],
        text: colors.zinc[700],
        bottom: colors.amber[50],
        'box-bottom': colors.amber[200],
        'strong-bottom': colors.amber[300],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      },
      'amber-d': {
        primary: colors.amber[50],
        secondary: colors.amber[200],
        accent: colors.zinc[400],
        text: colors.zinc[50],
        bottom: colors.amber[900],
        'box-bottom': colors.amber[800],
        'strong-bottom': colors.amber[700],
        link: colors.blue[900],
        success: colors.emerald[600],
        danger: colors.red[600],
        alert: colors.yellow[600],
        info: colors.cyan[600]
      }
    })
  ],
};
